# Generated by Django 3.2.13 on 2022-05-04 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'BUY'), (1, 'SELL'), (2, 'EXCHANGE')])),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.PositiveSmallIntegerField()),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CryptoAplication.status')),
            ],
        ),
    ]
